name: "Discord Bot"
slug: discord_bot
version: "1.0.0"

startup: services
boot: auto

options:
  DISCORD_TOKEN: ""
  CLIENT_ID: ""
  CHANNEL_ID: ""
  LOG_CHANNEL_ID: ""

schema:
  DISCORD_TOKEN: str
  CLIENT_ID: str
  CHANNEL_ID: str
  LOG_CHANNEL_ID: str

build:
  dockerfile: Dockerfile
