name: "Discord Bot X"
version: "latest"
slug: "discord_bot_x"
description: "Discord bot running as a Home Assistant add-on"
url: "https://github.com/darking2539/discord-bot-addon"

arch:
  - amd64
  - aarch64
  - armv7

startup: services
boot: auto
init: false

image: "ghcr.io/bestsvt/discord-bot"

options:
  DISCORD_TOKEN: ""
  CLIENT_ID: ""
  CHANNEL_ID: ""
  LOG_CHANNEL_ID: ""

schema:
  DISCORD_TOKEN: str
  CLIENT_ID: str
  CHANNEL_ID: str
  LOG_CHANNEL_ID: str

environment:
  DISCORD_TOKEN: "{options.DISCORD_TOKEN}"
  CLIENT_ID: "{options.CLIENT_ID}"
  CHANNEL_ID: "{options.CHANNEL_ID}"
  LOG_CHANNEL_ID: "{options.LOG_CHANNEL_ID}"
